import { Router } from 'express';
import { requireUrl } from '../lib/validation.js';
import { Semaphore } from '../lib/semaphore.js';
import type { Browser } from 'playwright';

const router = Router();

let browser: Browser | null = null;
let browserFailed = false;
const maxConcurrency = Number(process.env.PLAYWRIGHT_MAX_CONCURRENCY) || 3;
const semaphore = new Semaphore(maxConcurrency);

export function isBrowserAvailable(): boolean {
  return browser !== null && !browserFailed;
}

export async function initBrowser(): Promise<void> {
  try {
    const { chromium } = await import('playwright');
    browser = await chromium.launch({ headless: true });
    browserFailed = false;
    console.log(`[scrape] Playwright browser launched (max concurrency: ${maxConcurrency})`);
  } catch (err) {
    browserFailed = true;
    browser = null;
    console.log(`[scrape] Playwright not available, using mock mode (${(err as Error).message})`);
  }
}

export async function closeBrowser(): Promise<void> {
  if (browser) {
    await browser.close();
    browser = null;
    console.log('[scrape] Playwright browser closed');
  }
}

function getMockScrapeResult(url: string) {
  const domain = new URL(url).hostname;
  return {
    title: `Sample Page from ${domain}`,
    content: [
      `# Welcome to ${domain}`,
      '',
      'This is a mock scrape result generated by the PayGate demo server because Playwright is not available in this environment.',
      '',
      '## Main Content',
      '',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      '',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      '',
      '## Key Points',
      '',
      '- First important point about the topic',
      '- Second key insight from the page',
      '- Third relevant detail worth noting',
      '',
      `*Scraped from ${url}*`,
    ].join('\n'),
    url,
    scraped_at: new Date().toISOString(),
    _demo: true,
    _mock: true,
    _note: 'This is a demo response. In production, this endpoint returns real scraped content via Playwright.',
  };
}

router.post('/v1/scrape', async (req, res, next) => {
  try {
    const url = requireUrl(req.body?.url, 'url');

    // Mock mode when Playwright is not available
    if (!browser) {
      console.log(`[scrape] url="${url}" mode=MOCK status=200`);
      res.json(getMockScrapeResult(url));
      return;
    }

    await semaphore.acquire();
    const start = Date.now();
    let context;

    try {
      context = await browser.newContext();
      const page = await context.newPage();

      await page.goto(url, { timeout: 15_000, waitUntil: 'networkidle' });

      const html = await page.content();

      const { JSDOM } = await import('jsdom');
      const { Readability } = await import('@mozilla/readability');

      const dom = new JSDOM(html, { url });
      const article = new Readability(dom.window.document).parse();

      let markdown = '';
      let title = '';
      if (article) {
        title = article.title;
        const TurndownService = (await import('turndown')).default;
        const td = new TurndownService();
        markdown = td.turndown(article.content);
      }

      const elapsed = Date.now() - start;
      console.log(`[scrape] url="${url}" upstream_ms=${elapsed} status=200`);

      res.json({
        title,
        content: markdown,
        url,
        scraped_at: new Date().toISOString(),
      });
    } finally {
      if (context) await context.close();
      semaphore.release();
    }
  } catch (err) {
    next(err);
  }
});

export default router;
